# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asset.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool

_runtime_version = None

if _runtime_version is not None:
    _runtime_version.ValidateProtobufRuntimeVersion(
        _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "asset.proto"
    )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61sset.proto\x12\x05\x61sset"K\n\x07Uniform\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05stage\x18\x03 \x01(\t\x12\x15\n\rdefault_value\x18\x04 \x01(\t"\x7f\n\x06Shader\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rvertex_shader\x18\x02 \x01(\t\x12\x17\n\x0f\x66ragment_shader\x18\x03 \x01(\t\x12\x15\n\rshader_lib_id\x18\x04 \x01(\x05\x12 \n\x08uniforms\x18\x05 \x03(\x0b\x32\x0e.asset.Uniform"\x8a\x01\n\x08\x45nvelope\x12\x0e\n\x06\x61ttack\x18\x01 \x01(\x01\x12\x13\n\x0b\x61ttackCurve\x18\x02 \x01(\t\x12\r\n\x05\x64\x65\x63\x61y\x18\x03 \x01(\x01\x12\x12\n\ndecayCurve\x18\x04 \x01(\t\x12\x0f\n\x07sustain\x18\x05 \x01(\x01\x12\x0f\n\x07release\x18\x06 \x01(\x01\x12\x14\n\x0creleaseCurve\x18\x07 \x01(\t"h\n\nOscillator\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x16\n\x0emodulationType\x18\x02 \x01(\t\x12\x13\n\x0bharmonicity\x18\x03 \x01(\x01\x12\x10\n\x08partials\x18\x04 \x03(\t\x12\r\n\x05phase\x18\x05 \x01(\x01"\x97\x01\n\tToneSynth\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06volume\x18\x02 \x01(\x01\x12\x0e\n\x06\x64\x65tune\x18\x03 \x01(\x01\x12\x12\n\nportamento\x18\x04 \x01(\x01\x12!\n\x08\x65nvelope\x18\x05 \x01(\x0b\x32\x0f.asset.Envelope\x12%\n\noscillator\x18\x06 \x01(\x0b\x32\x11.asset.Oscillator"5\n\x04Tone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x05synth\x18\x02 \x01(\x0b\x32\x10.asset.ToneSynth"d\n\x05\x41sset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1d\n\x06shader\x18\x03 \x01(\x0b\x32\r.asset.Shader\x12\x19\n\x04tone\x18\x04 \x01(\x0b\x32\x0b.asset.Toneb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "asset_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_UNIFORM"]._serialized_start = 22
    _globals["_UNIFORM"]._serialized_end = 97
    _globals["_SHADER"]._serialized_start = 99
    _globals["_SHADER"]._serialized_end = 226
    _globals["_ENVELOPE"]._serialized_start = 229
    _globals["_ENVELOPE"]._serialized_end = 367
    _globals["_OSCILLATOR"]._serialized_start = 369
    _globals["_OSCILLATOR"]._serialized_end = 473
    _globals["_TONESYNTH"]._serialized_start = 476
    _globals["_TONESYNTH"]._serialized_end = 627
    _globals["_TONE"]._serialized_start = 629
    _globals["_TONE"]._serialized_end = 682
    _globals["_ASSET"]._serialized_start = 684
    _globals["_ASSET"]._serialized_end = 784
# @@protoc_insertion_point(module_scope)
